export class Labels {

    title: string;
    export: string;
    clean: string;
    region: string;
    choose: string;
    text: string;
    chart: string;
    image: string;
    upload: string;
    remove: string;
    figure: string;
    options: string;
    custom: string;
    items: string;
    rectangle: string;
    square: string;
    triangle: string;
    circle: string;
    bar: string;
    horizontal: string;
    stacked: string;
    grouped: string;
    area: string;
    mixed: string;
    table: string;
    filter: string;
    date: string;
    pie: string;
    line: string;
    doughnut: string;
    select: string;
    previewTitle: string;
    xAxisTitle: string;
    yAxisTitle: string;
    color: string;
    save: string;
    titleText: string;
    nml: string;
    ne: string;
    nna: string;

    constructor() {
        this.title = "JarWiz";
        this.export = "Export to image";
        this.clean = "Clean";
        this.region = "Region";
        this.choose = "Choose Template";
        this.text = "Add text";
        this.chart = "Add Chart";
        this.image = "Add Images";
        this.upload = "Upload Image";
        this.remove = "Remove";
        this.figure = "Add figure";
        this.options = "Options";
        this.custom = "Custom";
        this.items = "No items selected";
        this.rectangle = "Rectangle";
        this.square = "Square";
        this.triangle = "Triangle";
        this.circle = "Circle";
        this.bar = "Bar";
        this.horizontal = "Horizontal Bar";
        this.stacked = "Stacked Bar";
        this.grouped = "Grouped Bar";
        this.area = "Area";
        this.mixed = "Mixed";
        this.table = "Table";
        this.filter = "Filter";
        this.date = "Date Filter";
        this.pie = "Pie";
        this.line = "Line";
        this.doughnut = "Doughnut";
        this.select = "Select Attributes";
        this.previewTitle = "Preview";
        this.xAxisTitle = "x axis label";
        this.yAxisTitle = "y axis label";
        this.color = "Color";
        this.save = "Save";
        this.titleText = "Title";
        this.nml = "Nissan Motor Limited";
        this.nna = "Nissan North America";
        this.ne = "Nissan Europe";
    }
}