export class LabelEsp {
    title: string;
    export: string;
    clean: string;
    region: string;
    choose: string;
    text: string;
    chart: string;
    image: string;
    upload: string;
    remove: string;
    figure: string;
    options: string;
    custom: string;
    items: string;
    rectangle: string;
    square: string;
    triangle: string;
    circle: string;
    bar: string;
    map: string;
    horizontal: string;
    stacked: string;
    grouped: string;
    area: string;
    mixed: string;
    table: string;
    filter: string;
    date: string;
    pie: string;
    line: string;
    doughnut: string;
    select: string;
    previewTitle: string;
    xAxisTitle: string;
    yAxisTitle: string;
    color: string;
    save: string;
    titleText: string;
    nml: string;
    ne: string;
    nna: string;
    legend1: string;
    legend2: string;
    color1: string;
    color2: string;
    dummy: string;
    start: string;
    end: string;
    id: string;
    opacity: string;
    fill: string;
    fontFamily: string;
    textAlign: string;
    fontSize: string;
    char: string;
    lineHeight: string;
    style: string;
    language: string;
    confirm: string;
    clearAll: string;

    constructor() {
        this.title = "JarWiz";
        this.export = "Exportar";
        this.clean = "Limpiar";
        this.region = "Región"
        this.choose = "Elegir la plantilla";
        this.text = "Añadir texto";
        this.chart = "Agregar gráfico";
        this.image = "Añadir imágenes";
        this.upload = "Cargar imagen";
        this.remove = "Retirar";
        this.figure = "Añadir figura";
        this.options = "Opciones";
        this.custom = "Personalizado";
        this.items = "No hay elementos seleccionados";
        this.rectangle = "Rectángulo";
        this.square = "Cuadrado";
        this.triangle = "Triángulo";
        this.circle = "Circulo";
        this.bar = "Bar";
        this.map = "Mapa";
        this.horizontal = "Barra horizontal";
        this.stacked = "Barra apilada";
        this.grouped = "Barra Agrupada";
        this.area = "Zona";
        this.mixed = "Mezclado";
        this.table = "Mesa";
        this.filter = "Filtrar";
        this.date = "Filtro de fecha";
        this.pie = "Tarta";
        this.line = "Line";
        this.doughnut = "Rosquilla";
        this.select = "Seleccionar atributos";
        this.previewTitle = "Avance";
        this.xAxisTitle = "etiqueta del eje x";
        this.yAxisTitle = "etiqueta del eje y";
        this.color = "Color";
        this.save = "Salvar";
        this.titleText = "Título";
        this.nml = "Nissan Motor Limited";
        this.nna = "Nissan Norteamérica";
        this.ne = "Nissan Europa";
        this.legend1 = "Leyenda 1";
        this.legend2 = "Leyenda 2";
        this.color1 = "Color 1";
        this.color2 = "Color 2";
        this.dummy = "Datos ficticios";
        this.start = "Fecha de inicio";
        this.end = "Fecha final";
        this.id = "CARNÉ DE IDENTIDAD";
        this.opacity = "Opacidad";
        this.fill = "Llenar";
        this.fontFamily = "Familia tipográfica";
        this.textAlign = "Texto alineado";
        this.fontSize = "Tamaño de fuente";
        this.char = "Espaciado de Char";
        this.lineHeight = "Altura de la línea";
        this.style = "Estilo";
        this.language = "Idioma";
        this.confirm = "Estás seguro ?";
        this.clearAll = "Limpiar Todo";
    }
}