export class LabelFrench {

    title: string;
    export: string;
    clean: string;
    region: string;
    choose: string;
    text: string;
    chart: string;
    image: string;
    upload: string;
    remove: string;
    figure: string;
    options: string;
    custom: string;
    items: string;
    rectangle: string;
    square: string;
    triangle: string;
    circle: string;
    bar: string;
    map: string;
    horizontal: string;
    stacked: string;
    grouped: string;
    area: string;
    mixed: string;
    table: string;
    filter: string;
    date: string;
    pie: string;
    line: string;
    doughnut: string;
    select: string;
    previewTitle: string;
    xAxisTitle: string;
    yAxisTitle: string;
    color: string;
    save: string;
    titleText: string;
    nml: string;
    ne: string;
    nna: string;
    legend1: string;
    legend2: string;
    color1: string;
    color2: string;
    dummy: string;
    start: string;
    end: string;
    id: string;
    opacity: string;
    fill: string;
    fontFamily: string;
    textAlign: string;
    fontSize: string;
    char: string;
    lineHeight: string;
    style: string;
    language: string;
    confirm: string;

    constructor() {
        this.title = "JarWiz";
        this.export = "Exportation";
        this.clean = "Nettoyer";
        this.region = "Région";
        this.choose = "Choisir le modèle";
        this.text = "Ajouter du texte";
        this.chart = "Ajouter un graphique";
        this.image = "Ajouter des images";
        this.upload = "Télécharger une image";
        this.remove = "Retirer";
        this.figure = "Ajouter chiffre";
        this.options = "Options";
        this.custom = "Douane";
        this.items = "Aucun élément sélectionné";
        this.rectangle = "Rectangle";
        this.square = "Carré";
        this.triangle = "Triangle";
        this.circle = "Cercle";
        this.bar = "Bar";
        this.map = "Carte";
        this.horizontal = "Barre horizontale";
        this.stacked = "Barre empilée";
        this.grouped = "Barre groupée";
        this.area = "Zone";
        this.mixed = "Mixte";
        this.table = "Table";
        this.filter = "Filtre";
        this.date = "Filtre de date";
        this.pie = "Tarte";
        this.line = "Ligne";
        this.doughnut = "Donut";
        this.select = "Sélectionner les attributs";
        this.previewTitle = "Aperçu";
        this.xAxisTitle = "étiquette d'axe x";
        this.yAxisTitle = "étiquette d'axe y";
        this.color = "Couleur";
        this.save = "Sauvegarder";
        this.titleText = "Titre";
        this.nml = "Nissan Motor Limited";
        this.nna = "Nissan Amérique du Nord";
        this.ne = "Nissan Europe"
        this.legend1 = "Légende 1";
        this.legend2 = "Légende 2";
        this.color1 = "Couleur 1";
        this.color2 = "Couleur 2";
        this.dummy = "Données factices";
        this.start = "Date de début";
        this.end = "Date de fin";
        this.id = "ID";
        this.opacity = "Opacité";
        this.fill = "Remplir";
        this.fontFamily = "Famille de polices";
        this.textAlign = "Alignement du texte";
        this.fontSize = "Taille de police";
        this.char = "Espacement des caractères";
        this.lineHeight = "Hauteur de la ligne";
        this.style = "Style";
        this.language = "La langue";
        this.confirm = "Êtes-vous sûr ?";
    }
}