export class LabelJap {

    title: string;
    export: string;
    clean: string;
    region: string;
    choose: string;
    text: string;
    chart: string;
    image: string;
    upload: string;
    remove: string;
    figure: string;
    options: string;
    custom: string;
    items: string;
    rectangle: string;
    square: string;
    triangle: string;
    circle: string;
    bar: string;
    horizontal: string;
    stacked: string;
    grouped: string;
    area: string;
    mixed: string;
    table: string;
    filter: string;
    date: string;
    pie: string;
    line: string;
    doughnut: string;
    select: string;
    previewTitle: string;
    xAxisTitle: string;
    yAxisTitle: string;
    color: string;
    save: string;
    titleText: string;
    nml: string;
    nna: string;
    ne: string;
    legend1: string;
    legend2: string;
    color1: string;
    color2: string;
    dummy: string;
    start: string;
    end: string;
    map: string;
    id: string;
    opacity: string;
    fill: string;
    fontFamily: string;
    textAlign: string;
    fontSize: string;
    char: string;
    lineHeight: string;
    style: string;
    language: string;

    constructor() {
        this.title = "テキストを追加";
        // this.export = "画像にエクスポート";
        this.export = "輸出する";
        this.clean = "クリーン";
        this.region = "領域";
        this.choose = "こちらを選択";
        this.text = "テキストを追加";
        this.chart = "グラフを追加する";
        this.image = "画像を追加";
        this.upload = "画像をアップロードする";
        this.remove = "削除する";
        this.figure = "図を追加";
        this.options = "オプション";
        this.custom = "カスタム";
        this.items = "アイテムが選択されていません";
        this.rectangle = "矩形";
        this.square = "平方";
        this.triangle = "三角形";
        this.circle = "サークル";
        this.bar = "バー";
        this.horizontal = "水平バー";
        this.stacked = "積み上げ バー";
        this.grouped = "グループ化されたバー";
        this.area = "エリア";
        this.mixed = "混在";
        this.table = "表";
        this.filter = "フィルタ";
        this.date = "日付フィルター";
        this.pie = "パイ";
        this.line = "ライン";
        this.doughnut = "ドーナツ";
        this.select = "属性を選択";
        this.previewTitle = "タイトル";
        this.xAxisTitle = "x軸ラベル";
        this.yAxisTitle = "y軸ラベル";
        this.color = "色";
        this.save = "保存する";
        this.titleText = "タイトル";
        this.nml = "日産自動車株式会社";
        this.nna = "日産北米";
        this.ne = "日産ヨーロッパ";
        this.legend1 = "伝説1";
        this.legend2 = "伝説2";
        this.color1 = "カラー1";
        this.color2 = "カラー2";
        this.dummy = "ダミーデータ";
        this.start = "開始日";
        this.end = "終了日";
        this.map = "ヒートマップ";
        this.id = "私日";
        this.opacity = "不透明度";
        this.fill = "塗りつぶし";
        this.fontFamily = "フォントファミリー";
        this.textAlign = "テキスト整列";
        this.fontSize = "フォントサイズ";
        this.char = "文字間隔";
        this.lineHeight = "行の高さ";
        this.style = "スタイル";
        this.language = "言語";
    }
}