export class Labels {

    title: string;
    export: string;
    clean: string;
    region: string;
    choose: string;
    text: string;
    chart: string;
    image: string;
    upload: string;
    remove: string;
    figure: string;
    options: string;
    custom: string;
    items: string;
    rectangle: string;
    square: string;
    triangle: string;
    circle: string;
    bar: string;
    map: string;
    horizontal: string;
    stacked: string;
    grouped: string;
    area: string;
    mixed: string;
    table: string;
    filter: string;
    date: string;
    pie: string;
    line: string;
    doughnut: string;
    select: string;
    previewTitle: string;
    xAxisTitle: string;
    yAxisTitle: string;
    color: string;
    save: string;
    titleText: string;
    nml: string;
    ne: string;
    nna: string;
    legend1: string;
    legend2: string;
    color1: string;
    color2: string;
    dummy: string;
    start: string;
    end: string;
    id: string;
    opacity: string;
    fill: string;
    fontFamily: string;
    textAlign: string;
    fontSize: string;
    char: string;
    lineHeight: string;
    style: string;
    language: string;
    confirm: string;

    constructor() {
        this.title = "JarWiz";
        // this.export = "Export to image";
        this.export = "Export";
        this.clean = "Clean";
        this.region = "Region";
        this.choose = "Choose Template";
        this.text = "Add text";
        this.chart = "Add Chart";
        this.image = "Add Images";
        this.upload = "Upload Image";
        this.remove = "Remove";
        this.figure = "Add figure";
        this.options = "Options";
        this.custom = "Custom";
        this.items = "No items selected";
        this.rectangle = "Rectangle";
        this.square = "Square";
        this.triangle = "Triangle";
        this.circle = "Circle";
        this.bar = "Bar";
        this.map = "Map";
        this.horizontal = "Horizontal Bar";
        this.stacked = "Stacked Bar";
        this.grouped = "Grouped Bar";
        this.area = "Area";
        this.mixed = "Mixed";
        this.table = "Table";
        this.filter = "Filter";
        this.date = "Date Filter";
        this.pie = "Pie";
        this.line = "Line";
        this.doughnut = "Doughnut";
        this.select = "Select Attributes";
        this.previewTitle = "Preview";
        this.xAxisTitle = "x axis label";
        this.yAxisTitle = "y axis label";
        this.color = "Color";
        this.save = "Save";
        this.titleText = "Title";
        this.nml = "Nissan Motor Limited";
        this.nna = "Nissan North America";
        this.ne = "Nissan Europe";
        this.legend1 = "Legend 1";
        this.legend2 = "Legend 2";
        this.color1 = "Color 1";
        this.color2 = "Color 2";
        this.dummy = "Dummy Data";
        this.start = "Start Date";
        this.end = "End Date";
        this.id = "ID";
        this.opacity = "Opacity";
        this.fill = "Fill";
        this.fontFamily = "Font Family";
        this.textAlign = "Text Align";
        this.fontSize = "Font Size";
        this.char = "Char Spacing";
        this.lineHeight = "Line Height";
        this.style = "Style";
        this.language = "Language";
        this.confirm = "Are you sure ?";
    }
}